name: Ubuntu Workspace

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 300

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start SSH Shell
        uses: namespacelabs/breakpoint-action@v0
        with:
          duration: 5h
          authorized-users: aditya-dumps
