name: Ubuntu Workspace

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 300

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install tmate
        run: |
          sudo apt update
          sudo apt install -y tmate

      - name: Start tmate
        run: |
          tmate -S /tmp/tmate.sock new-session -d
          echo "Waiting for tmate..."

          timeout 60 tmate -S /tmp/tmate.sock wait tmate-ready || {
            echo "tmate failed to become ready"
            tmate -S /tmp/tmate.sock show-messages
            exit 1
          }

          echo "===== SSH CONNECTION ====="
          tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}'
          echo "=========================="

          sleep 18000
